version: "3"
services:
  backend_sw:
    container_name: backend_sw
    restart: always
    build: ./backend_sw
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db_sw
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
    networks:
      - sw-network
      
  db_sw:
    container_name: db_sw
    image: mysql:8.0
    volumes:
      - db_sw-data:/var/lib/mysql
    ports:
      - 3315:3306
    environment:
      MYSQL_DATABASE: Book_Store
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - sw-network

volumes:
  db_sw-data:
networks:
  sw-network:
